M48
; DRILL file {KiCad 7.0.2-0} date 2023 December 01, Friday 11:24:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-01T11:24:21-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X117.05Y-39.43
X117.05Y-45.21
T2
X119.6Y-86.57
X119.6Y-89.57
X119.64Y-62.9
X119.64Y-65.9
T0
M30
